cookie:
  expiry_days: 30
  key: "Giga2022"
  name: giga_vis
credentials:
  usernames:
    utkucanozturk:
      email: utku.ozturk@itu.int
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Utku Can
      last_name: Ozturk
      logged_in: False # Will be managed automatically
      password: 'xxx'
      roles:
      - admin
      - editor
      - viewer